### ISSUE TITLE
AsmContext get flush out when it loads another class during scanning a method

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-asm#1]
In this following code it shall check if there are current context already before set it:

```java
    public static void enterClass(String className) {
        AsmContext context = new AsmContext(Type.getObjectType(className).getClassName(), TYPE);
        current.set(context);
    }
```

Otherwise it might cause a trouble when it needs to load another class during scanning of a method. A real example is:

```java
@Mailer
@TemplateContext("/mail")
public class PostOffice extends Mailer.Util {

    @OnEvent
    public void sendHi(HiEvent hi, User user MailerContext context) {
        context.to(user.getEmail());
        context.from("support@mycomp.com");
        context.subject("Hi");
        String msg = hi.source();
        send(user, msg);
    }

}
```

During the process of scanning `sendHi` method in the above code, it needs to load class `HiEvent` and this operation flush out the current context of `sendHi` method:

![image](https://user-images.githubusercontent.com/216930/28247305-09a20e7c-6a71-11e7-87a2-a4bf9d15d292.png)

This issue triggered https://github.com/actframework/actframework/issues/307

**Comment by He-Pin** [comment]
Thanks for this project
